mark: ""

model_path: "stabilityai/stable-diffusion-2-1-base"

gpu: 2

# feature injection setting
start_step: 0
inject_step: 20
end_step: 50
layer_idx: [10,11,12,13,14,15]

# set seeds
seeds: [15207, 20394]

# set reference image infos
ref_image_infos: {
  dataset/cat_necklace_spoon/image/cat.jpg: a cat,
  dataset/cat_necklace_spoon/image/necklace.jpg: a woman wearing a necklace,
  dataset/cat_necklace_spoon/image/spoon.jpg: a metal spoon,
}
target_prompt: "a metal cat wearing a necklace"
ref_index: [ 2, 6, 5 ]
ca_scale: 0.6

# ref image setting
use_null_ref_prompts: False     # Whether or not to use an empty prompt when denoising reference images.
mask_weights: [2.5, 3.0, 2.0]        # The larger the mask_weight is, the higher attention is for the reference image.

negative_prompt: "lowres, bad anatomy, text, error, cropped, worst quality, low quality, normal quality, jpeg artifacts, blurry"