mark: ""

model_path: "runwayml/stable-diffusion-v1-5"

gpu: 0

# feature injection setting
start_step: 0
end_step: 50
layer_idx: [10,11,12,13,14,15]

# set seeds
seeds: [278,500,5765,23455,25846,53839932]

# set reference image infos
ref_image_infos: {
  dataset/freecustom/multi_concept/dog_hat_sunglasses_3/image/dog.jpg: a dog,
  dataset/freecustom/multi_concept/dog_hat_sunglasses_3/image/hat.jpg: a cat wearing a red and black hat,
  dataset/freecustom/multi_concept/dog_hat_sunglasses_3/image/sunglasses.jpg: a cat with sunglasses,
}
target_prompt: "a dog with sunglasses wearing a red and black hat"

# ref image setting
use_null_ref_prompts: False     # Whether or not to use an empty prompt when denoising reference images.
mask_weights: [3.0, 3.0, 3.0]   # The larger the mask_weight is, the higher attention is for the reference image.

negative_prompt: "lowres, bad anatomy, text, error, cropped, worst quality, low quality, normal quality, jpeg artifacts, blurry"
style_fidelity: 1 # The larger the style_fidelity, the more like the reference concepts, range of values: [0,1]