mark: ""

model_path: "stabilityai/stable-diffusion-2-1-base"

gpu: 0

# feature injection setting
start_step: 0
inject_step: 20
end_step: 50
layer_idx: [10,11,12,13,14,15]

# set seeds
seeds: [2, 278, 9358, 324091, 53839932]

ca_scale: 0.6

# set reference image infos
ref_image_infos: {
  dataset/dog_hat_frog/image/dog.jpg: a dog,
  dataset/dog_hat_frog/image/hat.jpg: a cat wearing a red and black hat,
  dataset/dog_hat_frog/image/frog.jpg: a paper frog,
}
target_prompt: "a dog wearing a paper hat"
ref_index: [ 2, 6, 5 ]
ca_scale: 0.6

# ref image setting
use_null_ref_prompts: False     # Whether or not to use an empty prompt when denoising reference images.
mask_weights: [3.0, 2.5, 2.0]   # The larger the mask_weight is, the higher attention is for the reference image.

negative_prompt: "lowres, bad anatomy, text, error, cropped, worst quality, low quality, normal quality, jpeg artifacts, blurry"