mark: ""

model_path: "runwayml/stable-diffusion-v1-5"

gpu: 1

# feature injection setting
start_step: 0
end_step: 50
layer_idx: [10,11,12,13,14,15]

# set seeds
seeds: [22,278,546,863,2485,5030,40211,135623]

# set reference image infos
ref_image_infos: {
  dataset/freecustom/multi_concept/dog_necklace_sunglasses_0/image/dog.jpg: a dog,
  dataset/freecustom/multi_concept/dog_necklace_sunglasses_0/image/necklace.jpg: a woman wearing a necklace,
  dataset/freecustom/multi_concept/dog_necklace_sunglasses_0/image/sunglasses.jpg: a woman wearing sunglasses,
}
target_prompt: "a dog wearing sunglasses and a necklace."

# ref image setting
use_null_ref_prompts: False     # Whether or not to use an empty prompt when denoising reference images.
mask_weights: [3.0, 3.0, 3.0]        # The larger the mask_weight is, the higher attention is for the reference image.

negative_prompt: "lowres, bad anatomy, text, error, cropped, worst quality, low quality, normal quality, jpeg artifacts, blurry"
style_fidelity: 1 # The larger the style_fidelity, the more like the reference concepts, range of values: [0,1]