mark: ""

model_path: "runwayml/stable-diffusion-v1-5"

gpu: 1

# feature injection setting
start_step: 0
end_step: 50
layer_idx: [10,11,12,13,14,15]

# set seeds
seeds: [94,20132,23450,27349,29731,57630]

# set reference image infos
ref_image_infos: {
  dataset/freecustom/multi_concept/beard_flower_thanos/image/beard.jpg: a man with beard,
  dataset/freecustom/multi_concept/beard_flower_thanos/image/flower.jpg: a man holding flowers,
  dataset/freecustom/multi_concept/beard_flower_thanos/image/thanos.jpg: Thanos
}
target_prompt: "Thanos with beard holding flowers"

# ref image setting
use_null_ref_prompts: False     # Whether or not to use an empty prompt when denoising reference images.
mask_weights: [3.0, 2.0, 2.0]        # The larger the mask_weight is, the higher attention is for the reference image.

negative_prompt: "lowres, bad anatomy, text, error, cropped, worst quality, low quality, normal quality, jpeg artifacts, blurry"
style_fidelity: 1 # The larger the style_fidelity, the more like the reference concepts, range of values: [0,1]