mark: ""

model_path: "stabilityai/stable-diffusion-2-1-base"

gpu: 2

# feature injection setting
start_step: 0
inject_step: 20
end_step: 50
layer_idx: [ 10, 11, 12, 13, 14, 15 ]

# set seeds
seeds: [ 1, 100, 1000, 430375 ]

# set reference image infos
ref_image_infos: { dataset/girl_hat_scarf/image/girl.jpg: a woman, dataset/girl_hat_scarf/image/hat.jpg: a cat wearing a hat, dataset/girl_hat_scarf/image/scarf.jpg: a floral scarf }
target_prompt: "a woman wearing a floral hat"
ref_index: [ 2, 6, 5 ]
# ref image setting
use_null_ref_prompts: False # Whether or not to use an empty prompt when denoising reference images.
mask_weights: [ 3.0, 3.0, 2.0 ] # The larger the mask_weight is, the higher attention is for the reference image.

negative_prompt: "lowres, bad anatomy, text, error, cropped, worst quality, low quality, normal quality, jpeg artifacts, blurry"
ca_scale: 0.6
