mark: ""

model_path: "stabilityai/stable-diffusion-2-1-base"

gpu: 1

# feature injection setting
start_step: 0
inject_step: 20
end_step: 50
layer_idx: [10,11,12,13,14,15]

# set seeds
seeds: [88,4956,8201]

ca_scale: 0.6

# set reference image infos
ref_image_infos: {
  dataset/hinton_spiderman/image/hinton.jpg: an old man,
  dataset/hinton_spiderman/image/spiderman.jpg: a man wearing a spiderman clothes,
  dataset/hinton_spiderman/image/scarf.jpg: a wool scarf
}
target_prompt: "an old man wearing wool spiderman clothes"
ref_index: [ 2, 6, 5 ]
ca_scale: 0.6

# ref image setting
use_null_ref_prompts: False     # Whether or not to use an empty prompt when denoising reference images.
mask_weights: [3.0, 3.0, 2.5]        # The larger the mask_weight is, the higher attention is for the reference image.

negative_prompt: "lowres, bad anatomy, text, error, cropped, worst quality, low quality, normal quality, jpeg artifacts, blurry"
