mark: ""

model_path: "runwayml/stable-diffusion-v1-5"

gpu: 1

# feature injection setting
start_step: 0
end_step: 50
layer_idx: [10,11,12,13,14,15]

# set seeds
seeds: [256,5030,8392,13765,40211,44927]

# set reference image infos
ref_image_infos: {
  dataset/freecustom/multi_concept/cat_scarf/image/cat-1.jpg: a cat,
  dataset/freecustom/multi_concept/cat_scarf/image/scarf.jpg: a dog wearing a scarf,
}
target_prompt: "a cat wearing a scarf on its neck."

# ref image setting
use_null_ref_prompts: False     # Whether or not to use an empty prompt when denoising reference images.
mask_weights: [3.0, 3.0]        # The larger the mask_weight is, the higher attention is for the reference image.

negative_prompt: "lowres, bad anatomy, text, error, cropped, worst quality, low quality, normal quality, jpeg artifacts, blurry"
style_fidelity: 1 # The larger the style_fidelity, the more like the reference concepts, range of values: [0,1]